name: Update CA Certificates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5" # Weekly on Friday at midnight UTC

jobs:
  update-certs:
    uses: installable-sh/docker/.github/workflows/update-certs.yml@main
    permissions:
      contents: write

  release:
    needs: update-certs
    if: needs.update-certs.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    permissions:
      contents: write
