name: CI & Release

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 0 * * 6" # Weekly on Saturday at midnight UTC
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: installable-sh/docker/.github/workflows/ci.yml@main

  release:
    needs: [ci]
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    uses: installable-sh/docker/.github/workflows/release.yml@main
    permissions:
      contents: write
